  import './globals.css'
  import { Caveat } from 'next/font/google'
  const font = Caveat({ subsets: ['latin'] })

  export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
  }

  export default function RootLayout({
    children,
  }: {
    children: React.ReactNode
  }) {
    return (
      <html lang="en" className={font.className}>
        <body className='noScroll'>
          {children}
        </body>
    </html>
  )
}
